# Generated by Django 2.2 on 2020-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinician_name', models.CharField(max_length=30, null=True)),
                ('date_reported', models.DateTimeField()),
                ('date_attended', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('identity', models.CharField(max_length=255)),
            ],
        ),
    ]
