# Generated by Django 2.2 on 2020-01-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('case_no', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CASE_NO')),
                ('drugs', models.IntegerField()),
                ('lab_test', models.IntegerField()),
                ('proff_fees', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('other_charges', models.IntegerField()),
                ('total_charges', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
